import type { Metadata } from "next";

import "./globals.css";
import NavBar from "@/components/navbar";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Smart Bikes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} h-screen w-screen   overflow-y-auto overflow-x-hidden antialiased`}
      >
        <nav>
          <NavBar />
        </nav>
        {children}
      </body>
    </html>
  );
}
